### ISSUE TITLE
Fix reload on polygon

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/cellmap#5]

**Comment by sacdallago** [comment]
Latest stack:

``` javascript
TypeError: Cannot read property '1' of undefined
    at Object.linear (http://cell.dallago.us/public/regression.js:11:473)
    at c (http://cell.dallago.us/public/regression.js:11:3422)
    at addToInteractionMap (http://cell.dallago.us/public/protein.js:190:31)
    at http://cell.dallago.us/public/protein.js:335:37
    at Array.forEach (native)
    at HTMLImageElement.img.onload (http://cell.dallago.us/public/protein.js:334:34)
protein.js:219 Will reload
```

**Comment by sacdallago** [comment]
Previous problem was fixed,  now getting

```javascript
Error: Invalid LatLng object: (NaN, 212)
    at o.LatLng (script.js:5)
    at Object.o.latLng (script.js:5)
    at e.initialize (script.js:7)
    at new e (script.js:5)
    at Object.o.circleMarker (script.js:7)
    at Object.success (ppi.js:416)
    at j (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at x (jquery.js:5)
    at XMLHttpRequest.b (jquery.js:5)
```

**Comment by sacdallago** [comment]
Closing for now, as this appears to be a very infrequent problem.
